version: '4'

services:
  postgres:
    container_name: keycloak-db
    image: postgres:17-alpine
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_DB=keycloak-service'
      - 'POSTGRES_PASSWORD=keycloak'
      - 'POSTGRES_USER=keycloak'
    ports:
      - '5438:5432'
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.1
    command: [ "start-dev", "--import-realm" ]
    environment:
      DB_VENDOR: POSTGRESQL
      DB_ADDR: postgresql
      DB_DATABASE: keycloak-service
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8181:8080"
    volumes:
      - ./docker/keycloak/realms/:/opt/keycloak/data/import/
    depends_on:
      - postgres
  loki:
    image: grafana/loki:main
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    ports:
      - "3100:3100"