version: '4'

services:
  keycloak-db:
    container_name: keycloak-db
    image: postgres:17-alpine
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_DB=inventory-service'
      - 'POSTGRES_PASSWORD=inventory'
      - 'POSTGRES_USER=inventory'
    ports:
      - '5438:5432'
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.1
    command: [ "start-dev", "--import-realm" ]
    environment:
      DB_VENDOR: POSTGRESQL
      DB_ADDR: 
    depends_on:
      - keycloak-db