version: '3.9'

services:
  flyway:
    image: 'flyway/flyway'
    command: '-url=jdbc:postgresql://airbnb-clone-db:5432/airbnb-clone -schemas=public -user=airbnbclone -password=airbnbclone -connectRetries=60 migrate'
    volumes:
      - './db/migration:/flyway/sql'
    depends_on:
      - airbnb-clone-db
  airbnb-clone-db:
    image: 'postgres:17-alpine'
    volumes:
      - airbnb-clone-data:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_DB=airbnb-clone'
      - 'POSTGRES_PASSWORD=airbnbclone'
      - 'POSTGRES_USER=airbnbclone'
    expose:
      - '5436'
    ports:
      - '5436:5432'

volumes:
  airbnb-clone-data:
