version: '3.9'

services:
  airbnb-clone-db:
    image: 'postgres:17-alpine'
    volumes:
      - airbnb-clone-data:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_DB=airbnb-clone'
      - 'POSTGRES_PASSWORD=airbnbclone'
      - 'POSTGRES_USER=airbnbclone'
    expose:
      - '5436'
    ports:
      - '5436:5436'

volumes:
  airbnb-clone-data:
